[versions]
assertk = "0.28.1"
coroutines = "1.10.2"
cucumber = "7.23.0"
exposed = "1.0.0-rc-3"
dependencyManagement = "1.1.4"
flyway = "11.17.0"
h2Database = "2.4.240"
jvm = "21" # remember that .github actions also defines a JDK version
junitPlatform = "6.0.1"
kotlin = "2.2.21"
kotlin-logging = "7.0.13"
mockk = "1.14.6"
spring-boot = "3.5.7"
springdoc-openapi = "1.8.0"
springmockk = "4.0.2"
java-uuid-generator = "5.1.1"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-spring-boot-starter = { module = "org.jetbrains.exposed:exposed-spring-boot-starter", version.ref = "exposed" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
h2database = { module = "com.h2database:h2", version.ref = "h2Database" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "java-uuid-generator" }

[plugins]
