[versions]
assertk = "0.28.1"
coroutines = "1.10.2"
dependencyManagement = "1.1.4"
kotlin = "2.2.21"
springBoot = "3.5.6"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }

[plugins]
