[versions]
dependencyManagement = "1.1.4"
kotlin = "2.2.21"
springBoot = "3.5.6"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependecyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
